Added finnish locale
Lissy93/dashy pull request #1339
Opened 2023-10-08 09:35 UTC by lordpansar

*Thank you for contributing to Dashy! So that your PR can be handled effectively, please populate the following fields (delete sections that are not applicable)*

**Category**: 
> One of: Other (please specify) - Added finnish locale

**Overview**
> Added finnish language locale

**Issue Number** _(if applicable)_ #00

**New Vars** _(if applicable)_
> N/A

**Screenshot** _(if applicable)_
> N/A

**Code Quality Checklist** _(Please complete)_
- [x] All changes are backwards compatible
- [x] All lint checks and tests are passing
- [x] There are no (new) build warnings or errors
- [ ] _(If a new config option is added)_ Attribute is outlined in the schema and documented
- [ ] _(If a new dependency is added)_ Package is essential, and has been checked out for security or performance
- [ ] Bumps version, if new feature added

2023-10-24 13:46 UTC, lordpansar commented
Bump :)

2023-10-27 20:02 UTC, Lissy93 reviewed
Hiya @lordpansar - This looks awesome, thanks for adding! And sorry for the late review/ 

There's just one small thing missing - add the following into [`/src/utils/languages.js`](https://github.com/lordpansar/dashy/blob/master/src/utils/languages.js)


```javascript
import fi from '@/assets/locales/fi.json';
```

and

```javascript
  { // Finish
    name: 'Suomalainen',
    code: 'fi',
    locale: fi,
    flag: '🇫🇮',
  },
  ```

There's a guide on how to do this [here](https://github.com/Lissy93/dashy/blob/master/docs/multi-language-support.md#adding-a-new-language), but let me know if you still need any help

2023-10-30 19:14 UTC, yesBad requested changes
I looked over these quiet quickly, but it certainty looks like using some AI/Translate to just get PR points sadly. Using words that no actual Finnish person would use really and has some old fragments of Swedish for whatever reason? I hope it's just a bad Finnish translation.... Goodluck 👍

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "no-results":"Inga Ei hakutuloksia",
Why is there a random "Inga" here?

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "enter-to-search-web":"Hae verkosta painamalla palautuspainiketta"
I wouldn't personally use the word "palautuspainike" instead I'd just have it "Hae verkosta painamalla ENTER:iä"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "remember-me-long-time":"Pitkä",
"A long time" -> "Pitkän ajan päästä", only Pitkä sounds so weird.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "proceed-to-dashboard":"Jatkaa Dashboard",
"Jatka Dashboardiin" sounds better

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "edit-config-button":"Muokkaa määritystä",
"Edit Config" -> "Muokkaa asetuksia", "määritystä" isn't a word I'd use here.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "edit-config-tab":"Muokkaa määritystä",
"Edit Config" -> "Muokkaa asetuksia", "määritystä" isn't a word I'd use here.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "edit-css-button":"Muokata Custom CSS",
I'd use "Muokkaa" instead of "Muokata"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "edit-cloud-sync-button":"Muokata pilvisynkronointi",
I'd use "Muokkaa" instead of "Muokata"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "cloud-sync-button":"Aktivoida pilvisynkronointi",
I'd use "Aktivoi" instead of "Aktivoida"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "backup-note":"On suositeltavaa tehdä varmuuskopio määrityksistä ennen muutosten tekemistä.",
I'd use "asetuksistasi" instead of "määrityksistä"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "reset-config-msg-l1":"Tämä poistaa kaikki käyttäjäasetukset paikallisesta tallennustilasta, mutta ei vaikuta sinun 'conf.yml'-file",
"-file" -> "tiedostoon"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "data-copied-msg":"Määritykset on kopioitu leikepöydälle",
Again "Määritykset" -> "Asetuksesi"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "reset-config-label":"Palauta määritykset",
"määritykset" -> "asetuksesi"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "css-note-l2":"Styles overrides tallennetaan vain paikallisesti, joten on suositeltavaa tehdä kopio omastasi CSS.",
"Styles overrides" -> "Tyyli ohitukset"

"omastasi CSS" -> "omista CSS muokkauksistasi"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "alternate-view-heading":"Muuttaa näkemystä",
"Muuttaa näkemystä" -> "Muuta näkymää"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "workspace":"Workspace",
Työpöytä

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "minimal":"Minimal"
Minimaalinen

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "layout-label":"Layout",
Asettelu

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "config-launcher-label":"Kokoonpano",
"kokoonpano" kind of works, but "asetukset" could make more sense.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "config-launcher-tooltip":"Päivitä kokoonpano",
"Päivitä asetukset" makes more sense imho.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "save-button":"Tallentaa",
Tallenna

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "save-button":"Tallentaa",
Tallenna

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "cancel-button":"Peruuttaa",
Peruuta

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "reset-toast":"Omat värit {theme} on poistettu"
"Omat värit teemalle {theme}"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "save-location-label":"Säästöpaikka",
Tallennuspaikka

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "preview-button":"Esikatsele muutokset",
"muutokset" -> "muutoksia"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "error-msg-save-mode":"Valitse Tallennustila: Paikallinen tai Tiedosto",
"tallennustila" -> "tallennuspaikka"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "rebuilding-status-1":"Luo uudelleen...",
"Luo" -> "Luodaan"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "success-msg":"Toipuminen onnistui",
"Toipuminen" cmon recovery?? -> "Toiminto"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "intro-l2":"All data är fullständigt end-to-end krypterad med AES, med ditt lösenord som nyckel.",
bro this is swedish... -> "Kaikki data on kokonaan päästä päähän salattu AES salauksella käyttämällä sinun salasanaasi avaimena."

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "backup-button-setup":"Varmuuskopioida",
Tee varmuuskopio

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "backup-id-label":"Varatunnuksesi",
Sinun varmuuskopion tunnus

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "backup-id-note":"Tätä käytetään palauttamiseen varmuuskopioista myöhemmin. Pidä se siis yhdessä salasanasi kanssa turvallisessa paikassa.",
Tätä käytetään varmuuskopiosi palauttamiseen myöhemmin.

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "restore-button":"Nollaa",
Restore doesn't mean nollaa. "Palauta"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "backup-success-msg":"Valmistettu ilman ongelmia",
"Toteuttettu onnistuneesti"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "restore-success-msg":"Kokoonpano on palautettu ilman ongelmia"
"Asetukset palautettu onnistuneesti"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "workspace":"Workspace-näkymä",
"Työpöytä-näkymä"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "modal":"Pop-Up Modal",
"Ponnahdusikkuna modaali", but yeah it sounds kinda better in English

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +    "edit-item":"Muokata",
Muokkaa

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "modal":"Pop-Up Modal",
"Ponnahdusikkuna modaali", but yeah it sounds kinda better in English

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "workspace":"Workspace View",
"Työpöytä-näkymä"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "edit-item":"Muokata",
Muokkaa

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "edit-section":"Muokata",
Muokkaa

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "move-section":"Muuttaa",
Siirtää

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "edit-app-config-tooltip":"Muut sovelluksen määritysvaihtoehdot",
"Muut sovelluksen asetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "save-disk-tooltip":"Tallenna kokoonpano levyllä olevaan conf.yml-tiedostoon. Tämä varmuuskopioi ja korvaa nykyiset määritykset",
"määritykset" -> "asetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "export-config-btn":"Vie kokoonpano",
"kokoonpano" -> "asetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "export-config-tooltip":"Tarkastele ja vie uutta kokoonpanoa joko tiedostoon tai leikepöydälle",
"Tarkastele ja vie uutta kokoonpanoa" -> "Tarkastele ja vie uudet asetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "cloud-backup-tooltip":"Tallenna määritysten salattu varmuuskopio pilveen",
"määritysten" -> "asetuksien"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "edit-raw-config-btn":"Muokkaa raw-määritystä",
"Muokkaa raaka-asetuksia"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "edit-raw-config-tooltip":"Tarkastele ja muokkaa raw-määritystä JSON-editorin kautta",
"muokkaa raw-määritystä" -> "Muokkaa raaka-asetuksia"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "save-stage-btn":"Tallentaa",
Tallenna

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "cancel-stage-btn":"Peruuttaa"
Peruuta

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "warning-msg-l1":"Seuraavat vaihtoehdot koskevat edistyneitä sovellusmäärityksiä.",
"sovellusmääräyksiä" -> "sovellusasetuksia"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "warning-msg-docs":"dokumentaatiota",
tarkista "dokumentaatiota" doesn't sound natural -> "dokumentaatiosta"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "export-title":"Vie kokoonpano",
"kokoonpano" -> "asetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "copy-clipboard-tooltip":"Kopioi kaikki sovellusmääritykset järjestelmän leikepöydälle YAML-muodossa",
"sovellusmääritykset" -> "sovellusasetukset"

2023-10-30 19:14 UTC, yesBad commented on src/assets/locales/fi.json
> +      "download-file-tooltip":"Lataa kaikki sovellusmääritykset laitteellesi YAML-tiedostona",
"sovellusmääritykset" -> "sovellusasetukset"

2023-10-30 19:14 UTC, yesBad requested changes
I looked over these quiet quickly, but it certainty looks like using some AI/Translate to just get PR points sadly. Using words that no actual Finnish person would use really and has some old fragments of Swedish for whatever reason? I hope it's just a bad Finnish translation.... Goodluck 👍

2023-10-30 19:59 UTC, lordpansar commented
Hi @yesBad !

Thank you for your input and review. Finnish is not my first language although I speak it. I used my head where I could and looked up some words I didn't know online. Apparently this wasn't up to par for a native speaker regarding choice of words etc.

It makes me kind of sad though that you jump to conclusions when I'm trying to contribute to a piece of OSS that I enjoy.

I was also hoping that I could provide a foundation where a native speaker would catch improper grammar/spelling and update them in a PR. Just like I did when I updated the Swedish locale 1-2 years ago.

I'll let a family member with better Finnish proficency go through this. Thanks once again for your review 😊

2023-10-30 20:14 UTC, yesBad commented
> Hi @yesBad !
> 
> Thank you for your input and review. Finnish is not my first language although I speak it. I used my head where I could and looked up some words I didn't know online. Apparently this wasn't up to par for a native speaker regarding choice of words etc.
> 
> It makes me kind of sad though that you jump to conclusions when I'm trying to contribute to a piece of OSS that I enjoy.

Sorry about that, just a lot of Finnish translations seem to be done with some AI/Translate API nowdays sadly. 👍 

Goodluck with the PR.

2023-10-30 20:26 UTC, lordpansar commented
np bro 😊

2023-11-12 10:35 UTC, closed without merging